//go:build linux

package sandbox

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math"
	"syscall"
	"unsafe"

	"github.com/elastic/go-seccomp-bpf/arch"
	"golang.org/x/net/bpf"
	"golang.org/x/sys/unix"
)

// This file implements a pure-Go (CGO_ENABLED=0) seccomp-BPF filter installer.
// It intentionally does NOT depend on libseccomp (cgo) so ghost can be built as
// a static, cross-compiled binary. It faithfully reproduces the subset of
// libseccomp behavior that core's Docker-format profile relies on:
//
//   - multi-architecture filtering that closes the x86 compat-ABI bypass. On
//     x86_64 a filter guarding only the native arch can be sidestepped by
//     issuing 32-bit syscalls (i386 via int 0x80, or the x32 ABI). Each arch the
//     profile declares gets its own AUDIT_ARCH-gated syscall dispatch, and any
//     arch the running syscall does not match falls through to the default
//     action (fail-closed). Note x32 and x86_64 share one AUDIT_ARCH id and are
//     distinguished only by the 0x40000000 bit on the syscall number; under a
//     default-deny profile x32 syscalls therefore match no x86_64 allow-cell and
//     are denied wholesale — the bypass is closed by blanket denial, not by an
//     x32 allowlist (which is fine: containers run ELF64, not x32).
//   - argument conditions, including SCMP_CMP_MASKED_EQ with a non-zero datum
//     ((arg & mask) == value), which core uses to permit clone only for thread
//     creation (CLONE_THREAD).
//   - a configurable default errno (defaultErrnoRet), which core sets to ENOSYS
//     so libc gracefully falls back to older syscalls instead of taking SIGSYS.
//
// Only elastic/go-seccomp-bpf's cgo-free `arch` subpackage (syscall name→number
// tables, AUDIT_ARCH ids, x32 mask) and x/net/bpf (instruction assembly) are
// reused; the profile→BPF translation and multi-arch dispatch are our own so we
// keep libseccomp's compat-ABI guarantees that the upstream high-level API drops.

// seccompProfile mirrors the Docker/libseccomp profile JSON that core
// (internal/sandbox/executor/security) is the single source of truth for. ghost
// only consumes this profile; it never authors policy.
type seccompProfile struct {
	DefaultAction   string           `json:"defaultAction"`
	DefaultErrnoRet *uint            `json:"defaultErrnoRet,omitempty"`
	Architectures   []string         `json:"architectures,omitempty"`
	Syscalls        []seccompSyscall `json:"syscalls,omitempty"`
}

type seccompSyscall struct {
	Names  []string     `json:"names"`
	Action string       `json:"action"`
	Args   []seccompArg `json:"args,omitempty"`
}

type seccompArg struct {
	Index    uint   `json:"index"`
	Value    uint64 `json:"value"`
	ValueTwo uint64 `json:"valueTwo,omitempty"`
	Op       string `json:"op"`
}

// BPF layout of struct seccomp_data: nr(u32) @0, arch(u32) @4, ip(u64) @8,
// args[6](u64) @16. All offsets are byte offsets into that struct.
const (
	seccompDataNROffset   = 0
	seccompDataArchOffset = 4
	seccompDataArgsOffset = 16
	sizeU32               = 4
	sizeU64               = 8
)

var nativeEndian binary.ByteOrder

func init() {
	var i uint16 = 0xABCD
	if (*[2]byte)(unsafe.Pointer(&i))[0] == 0xCD {
		nativeEndian = binary.LittleEndian
	} else {
		nativeEndian = binary.BigEndian
	}
}

// ApplySeccompFromJSON installs the Docker-format seccomp profile (passed inline
// as JSON, generated by core at runtime — single source of truth, no image
// dependency) as a filter on the current process. The filter is inherited
// across fork/execve, so applying it in ghost before the student command runs
// (exec mode: before execve; supervise mode: before fork) covers the command
// and all descendants. Empty input is a no-op (flag not passed). NoNewPrivs is
// set here and composes idempotently with Landlock.
func ApplySeccompFromJSON(data []byte) error {
	if len(data) == 0 {
		return nil
	}
	var p seccompProfile
	if err := json.Unmarshal(data, &p); err != nil {
		return fmt.Errorf("seccomp: parse profile: %w", err)
	}
	insts, err := buildProgram(&p)
	if err != nil {
		return err
	}
	raw, err := bpf.Assemble(insts)
	if err != nil {
		return fmt.Errorf("seccomp: assemble bpf: %w", err)
	}
	return loadFilter(raw)
}

// buildProgram translates the profile into a resolved list of BPF instructions.
//
// Structure (all conditional jumps skip a small, bounded distance; every
// long-distance hop is an unconditional 32-bit Jump, so instruction positions
// are stable in a single pass and no branch relaxation is needed):
//
//	load arch
//	for each declared arch:
//	    if arch == ID: fall into its block; else unconditional-jump to next arch
//	    load nr
//	    <arch syscall cells>
//	    unconditional-jump to default
//	default: RET defaultAction
//
// Any undeclared architecture matches no block and falls straight through to the
// default action — fail-closed, which is how core's default-deny profile blocks
// foreign ABIs (i386/x32) that a native-only filter would leave exposed.
func buildProgram(p *seccompProfile) ([]bpf.Instruction, error) {
	defAct, err := parseAction(p.DefaultAction, p.DefaultErrnoRet)
	if err != nil {
		return nil, err
	}

	prog := newProgram()
	defaultLabel := prog.newLabel()

	for _, archName := range p.Architectures {
		info, ok := archInfo(archName)
		if !ok {
			// Unknown/unsupported/typo'd arch name: fail fast. Silently skipping it
			// is dangerous — if EVERY declared arch is unrecognized, zero arch
			// blocks are emitted and the filter collapses to a bare RET
			// defaultAction. Under a default-ALLOW profile that means the intended
			// per-syscall denials silently vanish (the filter becomes inert). Refuse
			// to install a filter that does not mean what the profile declares.
			return nil, fmt.Errorf("seccomp: unrecognized architecture %q in profile", archName)
		}

		matchLabel := prog.newLabel()
		nextArchLabel := prog.newLabel()

		prog.load(seccompDataArchOffset, sizeU32)
		// arch == ID -> enter this block (skip the unconditional jump below).
		prog.jmpToOnTrue(bpf.JumpEqual, uint32(info.ID), matchLabel)
		// arch != ID -> skip the whole block.
		prog.jump(nextArchLabel)

		prog.setLabel(matchLabel)
		prog.load(seccompDataNROffset, sizeU32)
		if err := emitArchRules(prog, info, p.Syscalls); err != nil {
			return nil, err
		}
		// Unmatched syscalls in this arch take the default action.
		prog.jump(defaultLabel)

		prog.setLabel(nextArchLabel)
	}

	prog.setLabel(defaultLabel)
	prog.ret(defAct)

	return prog.assemble()
}

// emitArchRules emits, for one architecture, the per-syscall match cells. The
// syscall number is loaded into the accumulator before each cell. Each cell is
// self-contained with its own RET placed adjacent to its check, so conditional
// jumps never span more than a handful of instructions regardless of how large
// the allowlist is.
func emitArchRules(prog *program, info *arch.Info, syscalls []seccompSyscall) error {
	for _, sc := range syscalls {
		act, err := parseAction(sc.Action, nil)
		if err != nil {
			return fmt.Errorf("seccomp: action %q: %w", sc.Action, err)
		}

		for _, name := range sc.Names {
			nr, ok := resolveSyscall(info, name)
			if !ok {
				// Name not present on this arch (e.g. an x86-only name on
				// arm64). Skip: it cannot be invoked here, and leaving it
				// unlisted keeps the default action applying to it.
				continue
			}
			sysNum := uint32(nr | info.SeccompMask)
			skip := prog.newLabel()

			if len(sc.Args) == 0 {
				// Unconditional cell: nr != sysNum skips the RET (distance 1).
				prog.jmpToOnTrue(bpf.JumpNotEqual, sysNum, skip)
				prog.ret(act)
				prog.setLabel(skip)
				continue
			}

			// Conditional cell: nr != sysNum skips the whole entry; otherwise
			// the arg checks decide between the RET (all pass) and skip (any
			// fail). Arg checks clobber A, so reload nr before the next name.
			prog.jmpToOnTrue(bpf.JumpNotEqual, sysNum, skip)
			match := prog.newLabel()
			if err := emitConditions(prog, sc.Args, match, skip); err != nil {
				return err
			}
			prog.setLabel(match)
			prog.ret(act)
			prog.setLabel(skip)
			prog.load(seccompDataNROffset, sizeU32)
		}
	}
	return nil
}

// emitConditions emits the AND-combined argument checks for one syscall entry.
// All conditions must pass to reach onMatch; any failure jumps to onFail.
// Docker profiles use a single args array whose entries are AND'd together.
func emitConditions(prog *program, args []seccompArg, onMatch, onFail label) error {
	for i, a := range args {
		last := i == len(args)-1
		// Where to go when this individual condition passes: for the last
		// condition, that's the match; otherwise continue to the next check.
		var passLabel label
		if last {
			passLabel = onMatch
		} else {
			passLabel = prog.newLabel()
		}
		if err := emitCondition(prog, a, passLabel, onFail); err != nil {
			return err
		}
		if !last {
			prog.setLabel(passLabel)
		}
	}
	return nil
}

// emitCondition emits a single 64-bit argument comparison, split into hi/lo
// 32-bit halves (BPF operates on 32-bit words). On success it jumps to pass; on
// failure to fail. The argument is loaded fresh here, so callers need not
// preserve the accumulator.
func emitCondition(prog *program, a seccompArg, pass, fail label) error {
	// seccomp_data carries exactly args[0..5]. Reject a larger index BEFORE
	// computing any offset: argOffsets does uint32 arithmetic (16 + 8*index), so a
	// huge index would wrap around to a small, 4-aligned, in-bounds offset — the
	// filter would then load and compare the WRONG args[] field while seccomp(2)
	// still SUCCEEDS, silently changing the policy's meaning. Fail loudly instead.
	if a.Index > 5 {
		return fmt.Errorf("seccomp: arg index %d out of range (seccomp_data has args[0..5])", a.Index)
	}
	hiOff, loOff := argOffsets(a.Index)
	hi := uint32(a.Value >> 32)
	lo := uint32(a.Value)

	switch a.Op {
	case "SCMP_CMP_EQ":
		// hi==Vhi && lo==Vlo
		prog.load(hiOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpNotEqual, hi, fail)
		prog.load(loOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpNotEqual, lo, fail)
		prog.jump(pass)

	case "SCMP_CMP_NE":
		// hi!=Vhi || lo!=Vlo
		prog.load(hiOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpNotEqual, hi, pass)
		prog.load(loOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpNotEqual, lo, pass)
		prog.jump(fail)

	case "SCMP_CMP_MASKED_EQ":
		// (arg & mask) == value, where mask=Value, value=ValueTwo.
		mHi := uint32(a.Value >> 32)
		mLo := uint32(a.Value)
		dHi := uint32(a.ValueTwo >> 32)
		dLo := uint32(a.ValueTwo)
		prog.load(hiOff, sizeU32)
		prog.and(mHi)
		prog.jmpToOnTrue(bpf.JumpNotEqual, dHi, fail)
		prog.load(loOff, sizeU32)
		prog.and(mLo)
		prog.jmpToOnTrue(bpf.JumpNotEqual, dLo, fail)
		prog.jump(pass)

	case "SCMP_CMP_GE":
		// arg >= V: hi>Vhi || (hi==Vhi && lo>=Vlo)
		prog.load(hiOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpGreaterThan, hi, pass)
		prog.jmpToOnTrue(bpf.JumpNotEqual, hi, fail)
		prog.load(loOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpGreaterOrEqual, lo, pass)
		prog.jump(fail)

	case "SCMP_CMP_GT":
		// arg > V: hi>Vhi || (hi==Vhi && lo>Vlo)
		prog.load(hiOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpGreaterThan, hi, pass)
		prog.jmpToOnTrue(bpf.JumpNotEqual, hi, fail)
		prog.load(loOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpGreaterThan, lo, pass)
		prog.jump(fail)

	case "SCMP_CMP_LE":
		// arg <= V: hi<Vhi || (hi==Vhi && lo<=Vlo)
		prog.load(hiOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpLessThan, hi, pass)
		prog.jmpToOnTrue(bpf.JumpNotEqual, hi, fail)
		prog.load(loOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpLessOrEqual, lo, pass)
		prog.jump(fail)

	case "SCMP_CMP_LT":
		// arg < V: hi<Vhi || (hi==Vhi && lo<Vlo)
		prog.load(hiOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpLessThan, hi, pass)
		prog.jmpToOnTrue(bpf.JumpNotEqual, hi, fail)
		prog.load(loOff, sizeU32)
		prog.jmpToOnTrue(bpf.JumpLessThan, lo, pass)
		prog.jump(fail)

	default:
		return fmt.Errorf("seccomp: unsupported compare op %q", a.Op)
	}
	return nil
}

// --- minimal forward-only BPF assembler ---
//
// The generator emits only forward jumps. Conditional jumps (JumpIf) always
// target a nearby label — they skip a single syscall cell, so their skip
// distance is small and fits BPF's 8-bit conditional skip field. Every
// long-distance branch (skip an entire architecture block) is emitted as an
// unconditional Jump, whose skip is 32-bit. Because no conditional skip ever
// needs to grow, instruction positions never shift and a single resolution pass
// is exact — no branch relaxation, which is the subtle, bug-prone part of a
// general seccomp assembler.

type label int

type jumpFixup struct {
	at     int // index of the jump instruction to patch
	target label
	uncond bool         // true: bpf.Jump; false: bpf.JumpIf (SkipTrue)
	cond   bpf.JumpTest // for conditional jumps
	val    uint32       // for conditional jumps
}

type program struct {
	insts  []bpf.Instruction
	fixups []jumpFixup
	labels map[label]int
	next   label
}

func newProgram() *program {
	return &program{labels: make(map[label]int)}
}

func (p *program) newLabel() label {
	p.next++
	return p.next
}

// setLabel binds a label to the position of the next instruction to be emitted.
// All jumps target labels bound after the jump is emitted (forward-only).
func (p *program) setLabel(l label) {
	p.labels[l] = len(p.insts)
}

func (p *program) load(off uint32, size int) {
	p.insts = append(p.insts, bpf.LoadAbsolute{Off: off, Size: size})
}

func (p *program) and(mask uint32) {
	p.insts = append(p.insts, bpf.ALUOpConstant{Op: bpf.ALUOpAnd, Val: mask})
}

func (p *program) ret(action uint32) {
	p.insts = append(p.insts, bpf.RetConstant{Val: action})
}

// jmpToOnTrue jumps to target when (A cond val) holds, else falls through.
func (p *program) jmpToOnTrue(cond bpf.JumpTest, val uint32, target label) {
	p.fixups = append(p.fixups, jumpFixup{at: len(p.insts), target: target, cond: cond, val: val})
	p.insts = append(p.insts, bpf.JumpIf{Cond: cond, Val: val})
}

// jump unconditionally transfers control to target.
func (p *program) jump(target label) {
	p.fixups = append(p.fixups, jumpFixup{at: len(p.insts), target: target, uncond: true})
	p.insts = append(p.insts, bpf.Jump{})
}

// assemble resolves every forward jump to a concrete skip count.
func (p *program) assemble() ([]bpf.Instruction, error) {
	for _, f := range p.fixups {
		dest, ok := p.labels[f.target]
		if !ok {
			return nil, fmt.Errorf("seccomp: unresolved jump label %d", f.target)
		}
		skip := dest - f.at - 1
		if skip < 0 {
			return nil, fmt.Errorf("seccomp: backward jump not supported (at %d -> %d)", f.at, dest)
		}
		if f.uncond {
			p.insts[f.at] = bpf.Jump{Skip: uint32(skip)}
			continue
		}
		if skip > math.MaxUint8 {
			return nil, fmt.Errorf("seccomp: conditional jump too far (%d); generator invariant violated", skip)
		}
		p.insts[f.at] = bpf.JumpIf{Cond: f.cond, Val: f.val, SkipTrue: uint8(skip)}
	}
	return p.insts, nil
}

func argOffsets(index uint) (hi uint32, lo uint32) {
	base := uint32(seccompDataArgsOffset) + sizeU64*uint32(index)
	if nativeEndian == binary.LittleEndian {
		return base + sizeU32, base
	}
	return base, base + sizeU32
}

// seccomp return actions (SECCOMP_RET_*). ERRNO/KILL carry data in the low bits.
func parseAction(s string, errnoRet *uint) (uint32, error) {
	switch s {
	case "SCMP_ACT_ALLOW":
		return unix.SECCOMP_RET_ALLOW, nil
	case "SCMP_ACT_ERRNO":
		code := uint32(unix.EPERM) // fallback when defaultErrnoRet is absent.
		if errnoRet != nil {
			code = uint32(*errnoRet)
		}
		return unix.SECCOMP_RET_ERRNO | (code & unix.SECCOMP_RET_DATA), nil
	case "SCMP_ACT_KILL_PROCESS":
		return unix.SECCOMP_RET_KILL_PROCESS, nil
	case "SCMP_ACT_KILL_THREAD", "SCMP_ACT_KILL":
		return unix.SECCOMP_RET_KILL_THREAD, nil
	case "SCMP_ACT_TRAP":
		return unix.SECCOMP_RET_TRAP, nil
	case "SCMP_ACT_LOG":
		return unix.SECCOMP_RET_LOG, nil
	default:
		return 0, fmt.Errorf("seccomp: unsupported action %q", s)
	}
}

// syscallAliases maps libseccomp's canonical syscall names (used by core's
// Docker-format profiles) to the equivalent name in elastic's per-arch tables,
// which occasionally differ. libseccomp resolves these internally; since we look
// names up directly in the arch tables we must do the same, or a profile entry
// silently drops on an arch that spells the syscall differently — which under a
// default-deny profile would deny a syscall the policy meant to allow.
//
// The critical case is newfstatat: core's profile lists it (glibc's runtime stat
// on aarch64/arm), but elastic names that syscall fstatat (aarch64) or fstatat64
// (i386/arm). Dropping it breaks the dynamic loader (cannot stat libc.so.6).
// Each canonical name maps to an ordered list of candidate table names; the
// first present on the arch wins.
var syscallAliases = map[string][]string{
	"newfstatat": {"newfstatat", "fstatat", "fstatat64"},
	"fstatat64":  {"fstatat64", "fstatat", "newfstatat"},
}

// resolveSyscall looks up a profile syscall name in an arch's table, applying
// libseccomp-compatible name aliases. Returns the syscall number and whether it
// exists on this arch.
func resolveSyscall(info *arch.Info, name string) (int, bool) {
	if nr, ok := info.SyscallNames[name]; ok {
		return nr, true
	}
	for _, alias := range syscallAliases[name] {
		if nr, ok := info.SyscallNames[alias]; ok {
			return nr, true
		}
	}
	return 0, false
}

// archInfo maps Docker profile arch names to the cgo-free elastic arch tables.
func archInfo(name string) (*arch.Info, bool) {
	switch name {
	case "SCMP_ARCH_X86":
		return arch.I386, true
	case "SCMP_ARCH_X86_64":
		return arch.X86_64, true
	case "SCMP_ARCH_X32":
		return arch.X32, true
	case "SCMP_ARCH_AARCH64":
		return arch.AARCH64, true
	case "SCMP_ARCH_ARM":
		return arch.ARM, true
	default:
		return nil, false
	}
}

// loadFilter sets no_new_privs then installs the assembled filter via the
// seccomp(2) syscall. no_new_privs is required for an unprivileged process to
// install a filter, and once set cannot be unset.
//
// The filter is installed with SECCOMP_FILTER_FLAG_TSYNC so it applies to EVERY
// thread of the process, not just the calling one. This is essential: ghost is a
// Go program, and the goroutine that installs the filter may be migrated to a
// different OS thread before it forks/execs the student command (both call sites
// perform blocking work — LookPath, prlimit, forkExecLock — between install and
// fork). A thread-local (flag 0) filter would only be inherited from the exact
// thread that forks, so a migrated goroutine would run the student command
// unsandboxed. TSYNC closes that race by synchronizing all threads at install
// time; the previous libseccomp-based implementation set TSYNC by default, so
// this preserves that guarantee.
func loadFilter(raw []bpf.RawInstruction) error {
	filter := make([]unix.SockFilter, len(raw))
	for i, r := range raw {
		filter[i] = unix.SockFilter{Code: r.Op, Jt: r.Jt, Jf: r.Jf, K: r.K}
	}
	fprog := &unix.SockFprog{
		Len:    uint16(len(filter)),
		Filter: &filter[0],
	}

	if err := unix.Prctl(unix.PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0); err != nil {
		return fmt.Errorf("seccomp: set no_new_privs: %w", err)
	}
	// On success with TSYNC the syscall returns 0. On a TSYNC failure it returns
	// the (positive) TID of a thread that could not be synchronized rather than
	// setting errno, so a non-zero, non-errno return is also a failure.
	ret, _, errno := syscall.Syscall(unix.SYS_SECCOMP,
		uintptr(unix.SECCOMP_SET_MODE_FILTER),
		uintptr(unix.SECCOMP_FILTER_FLAG_TSYNC),
		uintptr(unsafe.Pointer(fprog)),
	)
	if errno != 0 {
		return fmt.Errorf("seccomp: load filter: %w", errno)
	}
	if ret != 0 {
		return fmt.Errorf("seccomp: load filter: could not synchronize thread %d to the filter", ret)
	}
	return nil
}
